/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cooltrickshome_DesktopMovieWallpaper */

#ifndef _Included_WallpaperChanger
#define _Included_WallpaperChanger
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_cooltrickshome_DesktopMovieWallpaper
	 * Method:    changeWallpaper
	 * Signature: (Ljava/lang/String;)I
	 */
	JNIEXPORT jint JNICALL Java_WallpaperChanger_putImage
	(JNIEnv*, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif